// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduledTask.proto

package timekiller.proto;

public final class ScheduledTaskProtoBuf {
  private ScheduledTaskProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterScheduledTaskRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegisterScheduledTaskRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    java.util.List<ScheduledTask>
        getScheduledTasksList();
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    ScheduledTask getScheduledTasks(int index);
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    int getScheduledTasksCount();
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    java.util.List<? extends ScheduledTaskOrBuilder>
        getScheduledTasksOrBuilderList();
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    ScheduledTaskOrBuilder getScheduledTasksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RegisterScheduledTaskRequest}
   */
  public static final class RegisterScheduledTaskRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RegisterScheduledTaskRequest)
      RegisterScheduledTaskRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterScheduledTaskRequest.newBuilder() to construct.
    private RegisterScheduledTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterScheduledTaskRequest() {
      scheduledTasks_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisterScheduledTaskRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterScheduledTaskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                scheduledTasks_ = new java.util.ArrayList<ScheduledTask>();
                mutable_bitField0_ |= 0x00000001;
              }
              scheduledTasks_.add(
                  input.readMessage(ScheduledTask.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          scheduledTasks_ = java.util.Collections.unmodifiableList(scheduledTasks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduledTaskProtoBuf.internal_static_RegisterScheduledTaskRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduledTaskProtoBuf.internal_static_RegisterScheduledTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RegisterScheduledTaskRequest.class, Builder.class);
    }

    public static final int SCHEDULEDTASKS_FIELD_NUMBER = 1;
    private java.util.List<ScheduledTask> scheduledTasks_;
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    @Override
    public java.util.List<ScheduledTask> getScheduledTasksList() {
      return scheduledTasks_;
    }
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    @Override
    public java.util.List<? extends ScheduledTaskOrBuilder>
        getScheduledTasksOrBuilderList() {
      return scheduledTasks_;
    }
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    @Override
    public int getScheduledTasksCount() {
      return scheduledTasks_.size();
    }
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    @Override
    public ScheduledTask getScheduledTasks(int index) {
      return scheduledTasks_.get(index);
    }
    /**
     * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
     */
    @Override
    public ScheduledTaskOrBuilder getScheduledTasksOrBuilder(
        int index) {
      return scheduledTasks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < scheduledTasks_.size(); i++) {
        output.writeMessage(1, scheduledTasks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < scheduledTasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, scheduledTasks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RegisterScheduledTaskRequest)) {
        return super.equals(obj);
      }
      RegisterScheduledTaskRequest other = (RegisterScheduledTaskRequest) obj;

      if (!getScheduledTasksList()
          .equals(other.getScheduledTasksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getScheduledTasksCount() > 0) {
        hash = (37 * hash) + SCHEDULEDTASKS_FIELD_NUMBER;
        hash = (53 * hash) + getScheduledTasksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RegisterScheduledTaskRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegisterScheduledTaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegisterScheduledTaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RegisterScheduledTaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RegisterScheduledTaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RegisterScheduledTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RegisterScheduledTaskRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegisterScheduledTaskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RegisterScheduledTaskRequest)
        RegisterScheduledTaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduledTaskProtoBuf.internal_static_RegisterScheduledTaskRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduledTaskProtoBuf.internal_static_RegisterScheduledTaskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RegisterScheduledTaskRequest.class, Builder.class);
      }

      // Construct using com.moonflying.timekiller.proto.ScheduledTaskProtoBuf.RegisterScheduledTaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getScheduledTasksFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (scheduledTasksBuilder_ == null) {
          scheduledTasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          scheduledTasksBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduledTaskProtoBuf.internal_static_RegisterScheduledTaskRequest_descriptor;
      }

      @Override
      public RegisterScheduledTaskRequest getDefaultInstanceForType() {
        return RegisterScheduledTaskRequest.getDefaultInstance();
      }

      @Override
      public RegisterScheduledTaskRequest build() {
        RegisterScheduledTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RegisterScheduledTaskRequest buildPartial() {
        RegisterScheduledTaskRequest result = new RegisterScheduledTaskRequest(this);
        int from_bitField0_ = bitField0_;
        if (scheduledTasksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            scheduledTasks_ = java.util.Collections.unmodifiableList(scheduledTasks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.scheduledTasks_ = scheduledTasks_;
        } else {
          result.scheduledTasks_ = scheduledTasksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RegisterScheduledTaskRequest) {
          return mergeFrom((RegisterScheduledTaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RegisterScheduledTaskRequest other) {
        if (other == RegisterScheduledTaskRequest.getDefaultInstance()) return this;
        if (scheduledTasksBuilder_ == null) {
          if (!other.scheduledTasks_.isEmpty()) {
            if (scheduledTasks_.isEmpty()) {
              scheduledTasks_ = other.scheduledTasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureScheduledTasksIsMutable();
              scheduledTasks_.addAll(other.scheduledTasks_);
            }
            onChanged();
          }
        } else {
          if (!other.scheduledTasks_.isEmpty()) {
            if (scheduledTasksBuilder_.isEmpty()) {
              scheduledTasksBuilder_.dispose();
              scheduledTasksBuilder_ = null;
              scheduledTasks_ = other.scheduledTasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              scheduledTasksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getScheduledTasksFieldBuilder() : null;
            } else {
              scheduledTasksBuilder_.addAllMessages(other.scheduledTasks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RegisterScheduledTaskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RegisterScheduledTaskRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ScheduledTask> scheduledTasks_ =
        java.util.Collections.emptyList();
      private void ensureScheduledTasksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          scheduledTasks_ = new java.util.ArrayList<ScheduledTask>(scheduledTasks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ScheduledTask, ScheduledTask.Builder, ScheduledTaskOrBuilder> scheduledTasksBuilder_;

      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public java.util.List<ScheduledTask> getScheduledTasksList() {
        if (scheduledTasksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scheduledTasks_);
        } else {
          return scheduledTasksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public int getScheduledTasksCount() {
        if (scheduledTasksBuilder_ == null) {
          return scheduledTasks_.size();
        } else {
          return scheduledTasksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public ScheduledTask getScheduledTasks(int index) {
        if (scheduledTasksBuilder_ == null) {
          return scheduledTasks_.get(index);
        } else {
          return scheduledTasksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder setScheduledTasks(
          int index, ScheduledTask value) {
        if (scheduledTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScheduledTasksIsMutable();
          scheduledTasks_.set(index, value);
          onChanged();
        } else {
          scheduledTasksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder setScheduledTasks(
          int index, ScheduledTask.Builder builderForValue) {
        if (scheduledTasksBuilder_ == null) {
          ensureScheduledTasksIsMutable();
          scheduledTasks_.set(index, builderForValue.build());
          onChanged();
        } else {
          scheduledTasksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder addScheduledTasks(ScheduledTask value) {
        if (scheduledTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScheduledTasksIsMutable();
          scheduledTasks_.add(value);
          onChanged();
        } else {
          scheduledTasksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder addScheduledTasks(
          int index, ScheduledTask value) {
        if (scheduledTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScheduledTasksIsMutable();
          scheduledTasks_.add(index, value);
          onChanged();
        } else {
          scheduledTasksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder addScheduledTasks(
          ScheduledTask.Builder builderForValue) {
        if (scheduledTasksBuilder_ == null) {
          ensureScheduledTasksIsMutable();
          scheduledTasks_.add(builderForValue.build());
          onChanged();
        } else {
          scheduledTasksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder addScheduledTasks(
          int index, ScheduledTask.Builder builderForValue) {
        if (scheduledTasksBuilder_ == null) {
          ensureScheduledTasksIsMutable();
          scheduledTasks_.add(index, builderForValue.build());
          onChanged();
        } else {
          scheduledTasksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder addAllScheduledTasks(
          Iterable<? extends ScheduledTask> values) {
        if (scheduledTasksBuilder_ == null) {
          ensureScheduledTasksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scheduledTasks_);
          onChanged();
        } else {
          scheduledTasksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder clearScheduledTasks() {
        if (scheduledTasksBuilder_ == null) {
          scheduledTasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          scheduledTasksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public Builder removeScheduledTasks(int index) {
        if (scheduledTasksBuilder_ == null) {
          ensureScheduledTasksIsMutable();
          scheduledTasks_.remove(index);
          onChanged();
        } else {
          scheduledTasksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public ScheduledTask.Builder getScheduledTasksBuilder(
          int index) {
        return getScheduledTasksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public ScheduledTaskOrBuilder getScheduledTasksOrBuilder(
          int index) {
        if (scheduledTasksBuilder_ == null) {
          return scheduledTasks_.get(index);  } else {
          return scheduledTasksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public java.util.List<? extends ScheduledTaskOrBuilder>
           getScheduledTasksOrBuilderList() {
        if (scheduledTasksBuilder_ != null) {
          return scheduledTasksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scheduledTasks_);
        }
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public ScheduledTask.Builder addScheduledTasksBuilder() {
        return getScheduledTasksFieldBuilder().addBuilder(
            ScheduledTask.getDefaultInstance());
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public ScheduledTask.Builder addScheduledTasksBuilder(
          int index) {
        return getScheduledTasksFieldBuilder().addBuilder(
            index, ScheduledTask.getDefaultInstance());
      }
      /**
       * <code>repeated .ScheduledTask scheduledTasks = 1;</code>
       */
      public java.util.List<ScheduledTask.Builder>
           getScheduledTasksBuilderList() {
        return getScheduledTasksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ScheduledTask, ScheduledTask.Builder, ScheduledTaskOrBuilder>
          getScheduledTasksFieldBuilder() {
        if (scheduledTasksBuilder_ == null) {
          scheduledTasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ScheduledTask, ScheduledTask.Builder, ScheduledTaskOrBuilder>(
                  scheduledTasks_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          scheduledTasks_ = null;
        }
        return scheduledTasksBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RegisterScheduledTaskRequest)
    }

    // @@protoc_insertion_point(class_scope:RegisterScheduledTaskRequest)
    private static final RegisterScheduledTaskRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RegisterScheduledTaskRequest();
    }

    public static RegisterScheduledTaskRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterScheduledTaskRequest>
        PARSER = new com.google.protobuf.AbstractParser<RegisterScheduledTaskRequest>() {
      @Override
      public RegisterScheduledTaskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterScheduledTaskRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterScheduledTaskRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RegisterScheduledTaskRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public RegisterScheduledTaskRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScheduledTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ScheduledTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    String getClassName();
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    String getMethod();
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>string corn = 3;</code>
     * @return The corn.
     */
    String getCorn();
    /**
     * <code>string corn = 3;</code>
     * @return The bytes for corn.
     */
    com.google.protobuf.ByteString
        getCornBytes();
  }
  /**
   * Protobuf type {@code ScheduledTask}
   */
  public static final class ScheduledTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ScheduledTask)
      ScheduledTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScheduledTask.newBuilder() to construct.
    private ScheduledTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScheduledTask() {
      className_ = "";
      method_ = "";
      corn_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScheduledTask();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScheduledTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              corn_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduledTaskProtoBuf.internal_static_ScheduledTask_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduledTaskProtoBuf.internal_static_ScheduledTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduledTask.class, Builder.class);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private volatile Object className_;
    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    @Override
    public String getClassName() {
      Object ref = className_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    @Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile Object method_;
    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    @Override
    public String getMethod() {
      Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    @Override
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORN_FIELD_NUMBER = 3;
    private volatile Object corn_;
    /**
     * <code>string corn = 3;</code>
     * @return The corn.
     */
    @Override
    public String getCorn() {
      Object ref = corn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        corn_ = s;
        return s;
      }
    }
    /**
     * <code>string corn = 3;</code>
     * @return The bytes for corn.
     */
    @Override
    public com.google.protobuf.ByteString
        getCornBytes() {
      Object ref = corn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        corn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      if (!getCornBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, corn_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      if (!getCornBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, corn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ScheduledTask)) {
        return super.equals(obj);
      }
      ScheduledTask other = (ScheduledTask) obj;

      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!getCorn()
          .equals(other.getCorn())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + CORN_FIELD_NUMBER;
      hash = (53 * hash) + getCorn().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ScheduledTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduledTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduledTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduledTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduledTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduledTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduledTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduledTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduledTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ScheduledTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduledTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduledTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ScheduledTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ScheduledTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ScheduledTask)
        ScheduledTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduledTaskProtoBuf.internal_static_ScheduledTask_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduledTaskProtoBuf.internal_static_ScheduledTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ScheduledTask.class, Builder.class);
      }

      // Construct using com.moonflying.timekiller.proto.ScheduledTaskProtoBuf.ScheduledTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        className_ = "";

        method_ = "";

        corn_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduledTaskProtoBuf.internal_static_ScheduledTask_descriptor;
      }

      @Override
      public ScheduledTask getDefaultInstanceForType() {
        return ScheduledTask.getDefaultInstance();
      }

      @Override
      public ScheduledTask build() {
        ScheduledTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ScheduledTask buildPartial() {
        ScheduledTask result = new ScheduledTask(this);
        result.className_ = className_;
        result.method_ = method_;
        result.corn_ = corn_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ScheduledTask) {
          return mergeFrom((ScheduledTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ScheduledTask other) {
        if (other == ScheduledTask.getDefaultInstance()) return this;
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.getCorn().isEmpty()) {
          corn_ = other.corn_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ScheduledTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ScheduledTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object className_ = "";
      /**
       * <code>string className = 1;</code>
       * @return The className.
       */
      public String getClassName() {
        Object ref = className_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private Object method_ = "";
      /**
       * <code>string method = 2;</code>
       * @return The method.
       */
      public String getMethod() {
        Object ref = method_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private Object corn_ = "";
      /**
       * <code>string corn = 3;</code>
       * @return The corn.
       */
      public String getCorn() {
        Object ref = corn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          corn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string corn = 3;</code>
       * @return The bytes for corn.
       */
      public com.google.protobuf.ByteString
          getCornBytes() {
        Object ref = corn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          corn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string corn = 3;</code>
       * @param value The corn to set.
       * @return This builder for chaining.
       */
      public Builder setCorn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        corn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string corn = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorn() {
        
        corn_ = getDefaultInstance().getCorn();
        onChanged();
        return this;
      }
      /**
       * <code>string corn = 3;</code>
       * @param value The bytes for corn to set.
       * @return This builder for chaining.
       */
      public Builder setCornBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        corn_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ScheduledTask)
    }

    // @@protoc_insertion_point(class_scope:ScheduledTask)
    private static final ScheduledTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ScheduledTask();
    }

    public static ScheduledTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScheduledTask>
        PARSER = new com.google.protobuf.AbstractParser<ScheduledTask>() {
      @Override
      public ScheduledTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScheduledTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScheduledTask> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ScheduledTask> getParserForType() {
      return PARSER;
    }

    @Override
    public ScheduledTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExecuteScheduledTaskRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExecuteScheduledTaskRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    String getClassName();
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    String getMethod();
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();
  }
  /**
   * Protobuf type {@code ExecuteScheduledTaskRequest}
   */
  public static final class ExecuteScheduledTaskRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExecuteScheduledTaskRequest)
      ExecuteScheduledTaskRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExecuteScheduledTaskRequest.newBuilder() to construct.
    private ExecuteScheduledTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExecuteScheduledTaskRequest() {
      className_ = "";
      method_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExecuteScheduledTaskRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExecuteScheduledTaskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduledTaskProtoBuf.internal_static_ExecuteScheduledTaskRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduledTaskProtoBuf.internal_static_ExecuteScheduledTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExecuteScheduledTaskRequest.class, Builder.class);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private volatile Object className_;
    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    @Override
    public String getClassName() {
      Object ref = className_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    @Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile Object method_;
    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    @Override
    public String getMethod() {
      Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    @Override
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExecuteScheduledTaskRequest)) {
        return super.equals(obj);
      }
      ExecuteScheduledTaskRequest other = (ExecuteScheduledTaskRequest) obj;

      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExecuteScheduledTaskRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExecuteScheduledTaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExecuteScheduledTaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExecuteScheduledTaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExecuteScheduledTaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExecuteScheduledTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExecuteScheduledTaskRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExecuteScheduledTaskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExecuteScheduledTaskRequest)
        ExecuteScheduledTaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduledTaskProtoBuf.internal_static_ExecuteScheduledTaskRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduledTaskProtoBuf.internal_static_ExecuteScheduledTaskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExecuteScheduledTaskRequest.class, Builder.class);
      }

      // Construct using com.moonflying.timekiller.proto.ScheduledTaskProtoBuf.ExecuteScheduledTaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        className_ = "";

        method_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduledTaskProtoBuf.internal_static_ExecuteScheduledTaskRequest_descriptor;
      }

      @Override
      public ExecuteScheduledTaskRequest getDefaultInstanceForType() {
        return ExecuteScheduledTaskRequest.getDefaultInstance();
      }

      @Override
      public ExecuteScheduledTaskRequest build() {
        ExecuteScheduledTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ExecuteScheduledTaskRequest buildPartial() {
        ExecuteScheduledTaskRequest result = new ExecuteScheduledTaskRequest(this);
        result.className_ = className_;
        result.method_ = method_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExecuteScheduledTaskRequest) {
          return mergeFrom((ExecuteScheduledTaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExecuteScheduledTaskRequest other) {
        if (other == ExecuteScheduledTaskRequest.getDefaultInstance()) return this;
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExecuteScheduledTaskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExecuteScheduledTaskRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object className_ = "";
      /**
       * <code>string className = 1;</code>
       * @return The className.
       */
      public String getClassName() {
        Object ref = className_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private Object method_ = "";
      /**
       * <code>string method = 2;</code>
       * @return The method.
       */
      public String getMethod() {
        Object ref = method_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExecuteScheduledTaskRequest)
    }

    // @@protoc_insertion_point(class_scope:ExecuteScheduledTaskRequest)
    private static final ExecuteScheduledTaskRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExecuteScheduledTaskRequest();
    }

    public static ExecuteScheduledTaskRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExecuteScheduledTaskRequest>
        PARSER = new com.google.protobuf.AbstractParser<ExecuteScheduledTaskRequest>() {
      @Override
      public ExecuteScheduledTaskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecuteScheduledTaskRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExecuteScheduledTaskRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ExecuteScheduledTaskRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ExecuteScheduledTaskRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterScheduledTaskRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterScheduledTaskRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScheduledTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScheduledTask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecuteScheduledTaskRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecuteScheduledTaskRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ScheduledTask.proto\"F\n\034RegisterSchedul" +
      "edTaskRequest\022&\n\016scheduledTasks\030\001 \003(\0132\016." +
      "ScheduledTask\"@\n\rScheduledTask\022\021\n\tclassN" +
      "ame\030\001 \001(\t\022\016\n\006method\030\002 \001(\t\022\014\n\004corn\030\003 \001(\t\"" +
      "@\n\033ExecuteScheduledTaskRequest\022\021\n\tclassN" +
      "ame\030\001 \001(\t\022\016\n\006method\030\002 \001(\tB8\n\037com.moonfly" +
      "ing.timekiller.protoB\025ScheduledTaskProto" +
      "Bufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RegisterScheduledTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterScheduledTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterScheduledTaskRequest_descriptor,
        new String[] { "ScheduledTasks", });
    internal_static_ScheduledTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ScheduledTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScheduledTask_descriptor,
        new String[] { "ClassName", "Method", "Corn", });
    internal_static_ExecuteScheduledTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ExecuteScheduledTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecuteScheduledTaskRequest_descriptor,
        new String[] { "ClassName", "Method", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
